#' Read the summary file from IPCHEM site
#' @description
#' The file is stored in the local environment and used by retrieve_info function.
#' Do not alter the downloaded file.
#' Otherwise, rerun this function.
#'
#' @returns a data frame called chem_summary stored in the environment
#' @export
#' @examples
#' load_summary()
#'
load_summary <- function() {
  url <- "https://ipchem.jrc.ec.europa.eu/public/IPCHEM_public_dataset_packages.csv"

  tryCatch(
    chem_summary <- get_csv_content(url),
    error = function(c) {
      stop("The summary file was not found. Check if the URL is working: \n ", url)
    }
  )

  chem_summary <- chg_col_names(chem_summary)
  chem_summary <<-
    chem_summary[!is.na(chem_summary$chemical_name), ]

  message(
    "Chem_summary is used by internal functions. Do not alter it. Run load_summary() if it was changed."
  )
}


#' Explore the summary file
#' @description
#' Works with the file generated by load_summary().
#' The function starts from one variable and builds upon it. It is the reverse way of filtering rows.
#'
#' @param ... vector or data frame used for filtering the results
#' @param target using the filters, the column that will be displayed for available values
#' @param filter filter the target using regular expression
#' @returns data frame with the first column as the target and all the other columns from filters
#' @export
#'
#' @examples
#' retrieve_info(target = media, filter = stringr::str_detect(media, "Water"))
#'
retrieve_info <- function(..., target, filter) {
  target <- rlang::as_string(rlang::ensym(target))

  flt <- rlang::enquo(filter)

  new_list <- expand_args(...)

  nms <- names(new_list)

  if (!exists("chem_summary")) {
    load_summary()
  }

  if (target %in% names(chem_summary)) {
    if (any(nms %in% names(chem_summary))) {
      nms <- nms[nms %in% names(chem_summary)]

      dts <- chem_summary
      mask <- rep(TRUE, nrow(dts))
      for (nm in nms) {
        mask <- mask & isin(dts[[nm]], new_list[[nm]], type = "any")
        # dts <- dts[dts[[nm]] %in% new_list[[nm]], ]
      }

      dts <- dts[mask, ]

      nms <- nms[nms != target] # remove duplicate columns
      dts <- dts[c(target, nms)]

      dts <- unique(dts)
    } else {
      dts <- unique(chem_summary[target])

      dts <- dts[order(dts[[target]]), ]
    }
  } else {
    stop("The target is not part of the summary file")
  }


  if (!rlang::quo_is_missing(flt)) {
    mask <- rlang::eval_tidy(flt, dts)
    dts <- dts[mask, ]
  }
  return(dts)
}


#' Create URL from summary
#' @description
#' Using the summary file create URL to download packages.
#' It is designed to be used in a pipeline with retrieve_info.
#'
#' @param ... filtering arguments. otherwise will mutate the full table
#' @returns dataframe
#' @export
#'
#' @examples
#' create_package_url()
#'
create_package_url <- function(...) {
  host <- "https://ipchem.jrc.ec.europa.eu/public"

  new_list <- expand_args(...)

  # check if there are empty values when argument is a data frame
  n <- length(new_list)
  mask <- rep(TRUE, length(new_list))

  for (i in 1:n){
    if (length(new_list[[i]]) == 0){
      mask[i] <- FALSE
    }
  }

  new_list <- new_list[mask]

  if (length(new_list) == 0){
    return(list())
  }


  nms <- names(new_list)

  if (!exists("chem_summary")) {
    load_summary()
  }

  targets <- c("dataset", "period", "package")

  if (all(targets %in% names(chem_summary))) {
    if (any(nms %in% names(chem_summary))) {
      nms <- nms[nms %in% names(chem_summary)]

      dts <- chem_summary

      for (nm in nms) {
        dts <- dts[dts[[nm]] %in% new_list[[nm]], ] # !!! NA VALUES
      }

      dts <- dts[targets]
      dts <- unique(dts)
    } else {
      dts <- unique(chem_summary[targets])
    }
    # browser()
    # dts <- na.omit(dts)

    for (col in targets) {
      dts[[col]] <- ifelse(is.na(dts[[col]]), "", dts[[col]])
    }

    url_list <- stringr::str_c(host, dts[["dataset"]], dts[["period"]], dts[["package"]], sep = "/")
  }

  return(url_list)
}

#' Get metadata info
#' @description
#' Using the name of a dataset bring the json metadata file.
#'
#' @param dataset character or vector with names of datasets
#' @returns list
#' @export
#'
#' @examples
#' retrieve_meta("NAIADES")
#'
retrieve_meta <- function(dataset) {
  # browser()
  meta_list <- list()

  for (i in seq_along(dataset)) {
    dts <- dataset[i]
    lst <- NULL

    url <- glue::glue("https://ipchem.jrc.ec.europa.eu/public/{dts}/IPCheM_{dts}_metadata.json")

    tryCatch(
      lst <- get_json_content(url),
      error = function(c) {
        message(stringr::str_c("Metadata information for", dataset[i], "was not found. Check the name", sep = " "))
        message("Skipping...")
      }
    )

    meta_list[[dataset[i]]] <- lst
  }

  return(meta_list)
}


#' Wrapper around retrieve_info
#' @description
#' Specific case of retrieve_info for target = media
#'
#' @param ... vector or data frame used for filtering the results
#' @param filter filter the target using regular expression
#' @returns data frame with the first column as the target and all the other columns from filters
#' @export
#'
#' @examples
#' retrieve_media(filter = stringr::str_detect(media, "Water"))
#'
retrieve_media <- function(..., filter) {
  dts <- retrieve_info(..., target = "media", filter = {{ filter }})

  return(dts)
}

#' Wrapper around retrieve_info
#' @description
#' Specific case of retrieve_info for target = dataset
#'
#' @param ... vector or data frame used for filtering the results
#' @param filter filter the target using regular expression
#' @returns data frame with the first column as the target and all the other columns from filters
#' @export
#'
#' @examples
#' retrieve_dataset(filter = stringr::str_detect(dataset, "^EMP"))
#'
retrieve_dataset <- function(..., filter) {
  dts <- retrieve_info(..., target = "dataset", filter = {{ filter }})

  return(dts)
}

#' Wrapper around retrieve_info
#' @description
#' Specific case of retrieve_info for target = period
#'
#' @param ... vector or data frame used for filtering the results
#' @param filter filter the target using regular expression
#' @returns data frame with the first column as the target and all the other columns from filters
#' @export
#'
#' @examples
#' retrieve_period(filter = (period > 2000))
#'
retrieve_period <- function(..., filter) {
  dts <- retrieve_info(..., target = "period", filter = {{ filter }})

  return(dts)
}


#' Wrapper around retrieve_info
#' @description
#' Specific case of retrieve_info for target = chemical_name
#'
#' @param ... vector or data frame used for filtering the results
#' @param filter filter the target using regular expression
#' @returns data frame with the first column as the target and all the other columns from filters
#' @export
#'
#' @examples
#' retrieve_chemical_name(filter = (stringr::str_detect(chemical_name, ".*clopido.*")))
#'
retrieve_chemical_name <- function(..., filter) {
  dts <- retrieve_info(..., target = "chemical_name", filter = {{ filter }})

  return(dts)
}


#' Wrapper around retrieve_info
#' @description
#' Specific case of retrieve_info for target = cas_number
#'
#' @param ... vector or data frame used for filtering the results
#' @param filter filter the target using regular expression
#' @returns data frame with the first column as the target and all the other columns from filters
#' @export
#'
#' @examples
#' retrieve_cas_number(filter = (cas_number %in% c("83003-12-7", "144171-61-9")))
#'
retrieve_cas_number <- function(..., filter) {
  dts <- retrieve_info(..., target = "cas_number", filter = {{ filter }})

  return(dts)
}

#' Wrapper around retrieve_info
#' @description
#' Specific case of retrieve_info for target = location
#'
#' @param ... vector or data frame used for filtering the results
#' @param filter filter the target using regular expression
#' @returns data frame with the first column as the target and all the other columns from filters
#' @export
#'
#' @examples
#' retrieve_location(filter = (stringr::str_detect(location, "ROU")))
#'
retrieve_location <- function(..., filter) {
  dts <- retrieve_info(..., target = "location", filter = {{ filter }})

  return(dts)
}


#' Wrapper around retrieve_info
#' @description
#' Modified case of retrieve_info for target = chemical_name, cas_number
#'
#' @param ... vector or data frame used for filtering the results
#' @param filter filter the target using regular expression
#' @returns data frame with the first column as the target and all the other columns from filters
#' @export
#'
#' @examples
#' retrieve_chem_cas(filter = ((isin(cas_number,"86")) & (isin(chemical_name, "naph"))))
#'
retrieve_chem_cas <- function(..., filter) {
  target <- c("chemical_name", "cas_number")

  flt <- rlang::enquo(filter)

  new_list <- expand_args(...)

  nms <- names(new_list)

  if (!exists("chem_summary")) {
    load_summary()
  }

  if ((target[1] %in% names(chem_summary)) & (target[2] %in% names(chem_summary))){
    if (any(nms %in% names(chem_summary))) {
      nms <- nms[nms %in% names(chem_summary)]

      dts <- chem_summary
      mask <- rep(TRUE, nrow(dts))
      for (nm in nms) {
        mask <- mask & isin(dts[[nm]], new_list[[nm]], type = "any")
        # dts <- dts[dts[[nm]] %in% new_list[[nm]], ]
      }

      dts <- dts[mask, ]

      nms <- nms[!(nms %in% target)] # remove duplicate columns
      dts <- dts[c(target, nms)]

      dts <- unique(dts)
    } else {
      dts <- unique(chem_summary[target])

      dts <- dts[order(dts[[target[1]]]), ]
    }
  } else {
    stop("The target is not part of the summary file")
  }


  if (!rlang::quo_is_missing(flt)) {
    mask <- rlang::eval_tidy(flt, dts)
    dts <- dts[mask, ]

    mask = (rowSums(is.na(dts)) == 0)
    dts <- dts[mask, ]

  }
  return(dts)
}
